language: c++
os: linux

install: sudo apt-get install ninja-build

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - cmake
      - cmake-data

compiler: clang-5.0

script: 
  - mkdir build && cd build
  - cmake -G Ninja -DDEBUG=1 -DCMAKE_C_COMPILER="clang-5.0" -DCMAKE_CXX_COMPILER="clang++-5.0" .. && ninja